minecraft_dependency=>=1.21.9 <=1.21.10
minecraft_version=1.21.9

fabric_version=0.134.0+1.21.9

malilib=0.26.7
litematica=0.24.8
tweakeroo=0.26.5
malilib_artifact=malilib-fabric-1.21.10
litematica_artifact=litematica-fabric-1.21.10
tweakeroo_artifact=tweakeroo-fabric-1.21.10

modmenu=16.0.0

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.8.2-1.21.9/quickshulker-2.8.2-1.21.9.jar

chesttracker=https://github.com/ponuing/ChestTracker/releases/download/v2.8.3%2B1.21.9/chesttracker-2.8.3%2B1.21.9.jar

